export const TorneosConstants = {

    POST_TORNAMENTS_FAILURE: "POST_TOURNAMENTS_FAILURE",
    POST_TORNAMENTS_REQUEST: "POST_TOURNAMENTS_REQUEST",
    POST_TORNAMENTS_SUCCESS: "POST_TOURNAMENTS_SUCCESS",

}

export default TorneosConstants