export const UserConstants = {

    USER_LOGIN_FAILURE: "LOGIN_FAILURE",
    USER_LOGIN_REQUEST: "LOGIN_REQUEST",
    USER_LOGIN_SUCCESS: "LOGIN_SUCCESS",

    USER_LOGOUT_FAILURE: "LOGOUT_FAILURE",
    USER_LOGOUT_REQUEST: "LOGOUT_REQUEST",
    USER_LOGOUT_SUCCESS: "LOGOUT_SUCCESS",

    USER_SELECT_PROVIDER: "SELECT_PROVIDER"
}

export default UserConstants